### ISSUE TITLE
Strategies for integrating into an existing codebase

### ISSUE THREAD

**Issue by gffhcks** [garnaat/placebo#9]
One thing I'm having trouble wrapping my head around, which maybe should be clarified in the readme: if I have an existing Boto application that I want to write unit tests for, and I want to use Placebo, how do I do so?

The main problem that I'm seeing is that loading and saving the stored responses happens on the boto *client* object, which is often created inside a class object or function; there's not much utility to passing clients as function arguments, because they're just containers for the API methods. (As far as I know, at least - feel free to correct me if passing them as arguments is better practice.)

If the client isn't being passed to the class or function, then as far as I can tell I have to pass parameters to it instead, telling it whether to save or load the placebo data, before I can access that behavior in my unit test. That also implies adding code to act on those parameters ("if save_placebo, then record and save; if load_placebo, then load the json before making any calls").

My concern with doing it this way is that it pollutes the module being tested with lots of scaffolding code that doesn't actually contribute to the application's purpose, or get used in production. Something like Mock, or Moto, for example, can typically be set up entirely in the test module, without affecting the original code's readability.

@garnaat - if I was going to use Placebo to test, say, a CLI tool - how would you recommend applying it while changing the application code as little as possible?

**Comment by garnaat** [comment]
FWIW, I've been struggling with this a bit, too.  The current model works great for me in some situations where I'm explicitly creating the boto3 clients.  But, as you say, that is not always the case.  Right now, with kappa, I'm trying to figure out a way to enable the recording of events with minimal messing around and I haven't come up with a great approach yet.  I'm not really worried about playing back the saved responses because, as you say, that is generally being done in the context of unit tests and a bit of mucking around to set things up is not a big problem.

I'm going to try to come up with something but if anyone has any ideas, please share them.

**Comment by garnaat** [comment]
One thing that makes it particularly difficult now is that you have to explicitly save the responses.  This is especially problematic with CLI apps like kappa as you have pointed out above.

But, really, there is no reason that we can't save each response to a file as it is recorded.  So, rather than save all responses to one big JSON file, we would save each response to a it's own file within a directory.  Similarly, playback would just point to that directory and read each response as it needs it.  We would have to carefully name the files and there would need to be a way to save multiple responses for a single service/operation but that seems doable.

**Comment by gffhcks** [comment]
Re: the directory idea. Would it be possible to point a `session` object at a responses directory, and have clients created from that session inherit it? This is how I'm envisioning it:

Say I have an `assume_role` function that can be passed a session as one of its arguments - for example, maybe I want to use an MFA session that I've previously established. I pass it a session that has Placebo attached to it, pointed to `./mocks`. The `assume_role` function creates an STS client from the passed session; any calls to that session then check in ./mocks/sts for saved responses before making the call to botocore. Now I have a way to tell my function to use mocked STS calls instead of real ones - just modify the session it uses, which lives outside the function scope

Or, on the opposite end: Say I'm using a single session for my entire application, or just the default boto3 session. In my code, I add a flag to attach placebo to the session. When placebo is attached (in 'save' mode), everything runs exactly the same, except that every client created from the session automatically stores every response to every call in the appropriate `./mocks/...` subdirectory. Now I can build mocked responses for an entire execution by only modifying one small part of the code - essentially adding a single 'record' button.

**Comment by garnaat** [comment]
The ``attach`` function could accept another param which would be the path to the directory where responses would be stored/read from.

**Comment by garnaat** [comment]
Actually, I'm not sure how that would work since ``attach`` would have no way to actually associated the path with newly created sessions.

**Comment by garnaat** [comment]
I've been trying some things out.  Here's what I currently have in place for testing kappa, a CLI tool.

In kappa itself, I added an additional option called ``--record-path <path>``.  If provided, this points to the path where the individual response files should be saved.  In addition, I import the ``placebo`` module in my main control module and if a recording path is passed on the command line my control class calls a function in ``placebo`` to tell it about the recording path.  Also, my control class creates my boto3 ``Session`` objects and that code calls ``placebo.atttach()`` on each session it creates.  That's all I am to do in kappa.

In my unit tests, there is a bit of set up but its only a few lines of code and I can integrate that with my unit tests pretty easily.

Does that sound like a reasonable approach?  It would be great to come up with a way to enable recording data without any modifications to the target program but I've not been able to come up with a way to make that happen.

**Comment by gffhcks** [comment]
So you're only calling attach on each session providing placebo with a path, and don't need to do anything to the individual clients, right? Did that require any modification to placebo?

Can you upload the branch for Kappa? I'd like to see the code.

I agree that recording without any modification to the target would be ideal. If that's not possible or practical then I think only requiring actions on the `boto3.Session` object is 'good enough'. Sessions already need to be kept track of because they handle credentials, but as far as I know clients can be treated as stateless if they inherited their credentials from the session - they don't hold any data that you actually need to care about, they just implement the API methods. Putting the record/save/load actions on clients adds state to them, so now they have to be tracked and handled in ways that they might not have been before.

(Am I wrong in thinking clients can be treated as stateless? I'm not overly familiar with the inner workings of boto3 but I've never come across a reason to care about the 'contents' of a client object - I'd like to be able to maintain that assumption when adding Placebo to a project.)

**Comment by garnaat** [comment]
It did require some changes in placebo.  I'll get a PR up for placebo and also get the kappa changes committed to my current WIP branch and update this thread.

Clients are stateless.  And I think these changes to placebo are more consistent with that since the decision to record or not is made based on the value of global state in the placebo module itself, not on any action in the client.  So, basically, if the global variable for recording_path in placebo is not None at the time the client is created, requests will be recorded.  So the starting and stopping of the recording is no longer done with methods in ``meta.placebo``.

I'm sure there is some way to make this happen in a way that doesn't require the client app to know anything about placebo but I haven't figured that out yet and at this point I really just need a decent way to handle this even if it is not optimal.

**Comment by gffhcks** [comment]
This makes perfect sense to me. Looking forward to seeing the code.

**Comment by garnaat** [comment]
Please review the changes on this on PR #14 when you get a chance.  Still more work to do but I think it's better.

**Comment by avs3323** [comment]
Hi,

This looks really cool to me!

I'll try it out and let you know how it works

**Comment by gffhcks** [comment]
I finally got around to implementing the refactor in my code and the new design works like a charm. Handling multiple sessions in the same run is a bit of a pain, but I think #20 will be a huge help for this.

@garnaat I don't know if you want to keep this open for tracking additional implementation changes but I'm totally satisfied. Placebo is now about a thousand times more usable for me.

**Comment by garnaat** [comment]
Awesome!  I think I'll close this for now.
